name: Create Comms issues weekly
on:
  schedule:
    - cron: "20 15 * * 3"  # Wed 15:20 UTC
  workflow_dispatch: {}

jobs:
  call:
    uses: ./.github/workflows/reusable-create-issues.yml
    with:
      team_label: comms
      min_issues: 1
      max_issues: 4
    secrets: inherit
